export 'package:findjob_app/widgets/item_oferta_dos.dart';
export 'package:findjob_app/widgets/item_oferta_tres.dart';
export 'package:findjob_app/widgets/item_oferta.dart';
export 'package:findjob_app/widgets/custom_navigationbar.dart';
export 'package:findjob_app/widgets/job_image.dart';
export 'package:findjob_app/widgets/register_form.dart';
export 'package:findjob_app/widgets/card_container.dart';
export 'package:findjob_app/widgets/auth_background.dart';
export 'package:findjob_app/widgets/postulantes.dart';
